// algorithms.js
export const pllAlgorithms = [
  { group: "Adjacent Corner Swap", name: "Aa", img: "./images/pll_Aa.png", alg: "x R' U R' D2 R U' R' D2 R2 x'", display:"x 151 D2 421 D2 44 x'"},
  { group: "Adjacent Corner Swap", name: "Ab", img: "./images/pll_Ab.png", alg: "x R2 D2 R U R' D2 R U' R x'", display:"x 11 D2 421 DD 44 x'"},
  { group: "Diagonal Corner Swap", name: "E",  img: "./images/pll_E.png",  alg: "x' R U' R' D R U R' D' R U R' D R U' R' D' x", display:"x' 421D 451D' 451D 421D' x" ,allowRandomU: false},
  { group: "Adjacent Corner Swap", name: "F",  img: "./images/pll_F.png",  alg: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R", display:"123 4512 1644 2124 5154" }, 
  { group: "Adjacent Corner Swap", name: "Ga", img: "./images/pll_Ga.png", alg: "R2 U R' U R' U' R U' R2 U' D R' U R D'", display:"445151 24244 2D 154D'" },
  { group: "Adjacent Corner Swap", name: "Gb", img: "./images/pll_Gb.png", alg: "R' U' R U D' R2 U R' U R U' R U' R2 D", display:"124 5D' 44515 424211D" },
  { group: "Adjacent Corner Swap", name: "Gc", img: "./images/pll_Gc.png", alg: "R2 U' R U' R U R' U R2 U D' R U' R' D", display:"11242451544 5D' 421D" },
  { group: "Adjacent Corner Swap", name: "Gd", img: "./images/pll_Gd.png", alg: "R U R' U' D R2 U' R U' R' U R' U R2 D'", display:"451 2D 44242451544D'" },
  { group: "Edges Only",           name: "H",  img: "./images/pll_H.png",  alg: "M2 U M2 U2 M2 U M2", display:"M2 U M2 U2 M2 U M2" ,  allowRandomU: false},
  { group: "Adjacent Corner Swap", name: "Ja", img: "./images/pll_Ja.png", alg: "x R2 F R F' R U2 r' U r U2 x'", display:"x 1164 3422 (1)5(4)22" },
  { group: "Adjacent Corner Swap", name: "Jb", img: "./images/pll_Jb.png", alg: "R U R' F' R U R' U' R' F R2 U' R'", display:"4513 4512 1644 212" },
  { group: "Diagonal Corner Swap", name: "Na", img: "./images/pll_Na.png", alg: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'", display:"4515 4513 4512 1644 2155421" ,allowRandomU: false },
  { group: "Diagonal Corner Swap", name: "Nb", img: "./images/pll_Nb.png", alg: "R' U R U' R' F' U' F R U R' F R' F' R U' R", display:"1542 1326 4512 42(6)4(3)" ,allowRandomU: false},
  { group: "Adjacent Corner Swap", name: "Ra", img: "./images/pll_Ra.png", alg: "R U' R' U' R U R D R' U' R D' R' U2 R'", display:"4513 422 122 1645 4221" },
  { group: "Adjacent Corner Swap", name: "Rb", img: "./images/pll_Rb.png", alg: "R2 F R U R U' R' F' R U2 R' U2 R", display:"1164 5421 3422 1554" },
  { group: "Adjacent Corner Swap", name: "T",  img: "./images/pll_T.png",  alg: "R U R' U' R' F R2 U' R' U' R U R' F'", display:"4512 1644 2124 513" },
  { group: "Edges Only",           name: "Ua", img: "./images/pll_Ua.png", alg: "U2 R U' R U R U R U' R' U' R2", display:"4515 1244 215154" },
  { group: "Edges Only",           name: "Ub", img: "./images/pll_Ub.png", alg: "U2 R2 U R U R' U' R' U' R' U R' U2", display:"1512 444 2154 511" },
  { group: "Diagonal Corner Swap", name: "V",  img: "./images/pll_V.png",  alg: "U' R' U R' U' y R' F' R2 U' R' U R' F R F y' U", display:"4245124D'42D 11244D'11" },
  { group: "Diagonal Corner Swap", name: "Y",  img: "./images/pll_Y.png",  alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'", display:"642124513 4512 1643" },
  { group: "Edges Only",           name: "Z",  img: "./images/pll_Z.png",  alg: "M' U' M2 U' M2 U' M' U2 M2 U", display:"M U M2 U M2 U M U2 M2 U'" ,allowRandomU: false }
];

export const collAlgorithms = [
  { group: "P", name: "P1", img: "./images/coll_p1.png", alg: "R U2 R2 U' R2 U' R2 U2 R", display: "4 22 11 2 44 2 11 22 4" },
  { group: "P", name: "P2", img: "./images/coll_p2.png", alg: "R U R' U' R' F R2 U R' U' R U R' U' F'", display: "4512 164 4512 4512 3" },
  { group: "P", name: "P3", img: "./images/coll_p3.png", alg: "F U R U' R' U R U' R' R' F' R U R U' R'", display: "6 5421 5421 134 5421" },
  { group: "P", name: "P4", img: "./images/coll_p4.png", alg: "R U R' U F' R U2 R U2 R' U2 R' F R", display: "4515 3422 422122 164" },
  //{ group: "P", name: "P4", img: "./images/coll_p4.png", alg: "R U' L' U R' U L U L' U L", display: "42 85 15 75857" },
  { group: "P", name: "P5", img: "./images/coll_p5.png", alg: "R' U' F' R U R' U' R' F R2 U2 R' U2 R", display: "12345121644 221224" },
  { group: "P", name: "P6", img: "./images/coll_p6.png", alg: "R' F' U' F U' R U S' R' U R S", display: "1326 245S' 154S" },

  { group: "H", name: "H1", img: "./images/coll_h1.png", alg: "R U2 R' U' R U R' U' R U' R'", display: "42212 4512 421", allowRandomU: false },
  { group: "H", name: "H2", img: "./images/coll_h2.png", alg: "F R U R' U' R U R' U' R U R' U' F'", display: "6 4512 4512 4512 3", allowRandomU: false },
  { group: "H", name: "H3", img: "./images/coll_h3.png", alg: "R U R' U R U L' U R' U' L", display: "4515 4585 127" },
  { group: "H", name: "H4", img: "./images/coll_h4.png", alg: "F R U' R' U R U2 R' U' R U R' U' F'", display: "6 4215 42212 4512 3" },

  { group: "U", name: "U1", img: "./images/coll_u1.png", alg: "R U R' U R U2 R' R' U' R U' R' U2 R", display: "4515 4221 1242 1224" },
  //{ group: "U", name: "U2", img: "./images/coll_u2.png", alg: "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R", display: "1 y-perm 4" },
  { group: "U", name: "U2", img: "./images/coll_u2.png", alg: "r U R' U' r' F R2 U' R' U' R U2 R' U' F'", display: "(4)512 (1)644 2124 22 123" },
  { group: "U", name: "U3", img: "./images/coll_u3.png", alg: "R2 D' R U2 R' D R U2 R", display: "11 D' 4221 D 4224" },
  { group: "U", name: "U4", img: "./images/coll_u4.png", alg: "R2 D R' U2 R D' R' U2 R'", display: "44 D 1224 D' 1221" },
  { group: "U", name: "U5", img: "./images/coll_u5.png", alg: "F R U' R' U R U R' U R U' R' F'", display: "6 4215 4515 421 3" },
  { group: "U", name: "U6", img: "./images/coll_u6.png", alg: "R2 D' R U R' D R U R U' R' U' R", display: "11 D' 451 D 4542124" },

  { group: "T", name: "T1", img: "./images/coll_t1.png", alg: "R U2 R' U' R U' R2 U2 R U R' U R", display: "4221 2421 1224 5154" },
  { group: "T", name: "T2", img: "./images/coll_t2.png", alg: "R U' R' U2 L R U' R' U L' ", display: "42155 7 4215 8" },
  { group: "T", name: "T3", img: "./images/coll_t3.png", alg: "r U R' U' r' F R F'", display: "(4)512 (1)643" },
  { group: "T", name: "T4", img: "./images/coll_t4.png", alg: "l' U' L U l F' L' F", display: "(8)275 (7)386" },
  { group: "T", name: "T5", img: "./images/coll_t5.png", alg: "F R U R' U' R U' R' U' R U R' F'", display: "6 4512 4212 4513" },
  { group: "T", name: "T6", img: "./images/coll_t6.png", alg: "R' U R2 D r' U2 r D' R2 U' R", display: "1544 D (1)55(4) D' 1124" },

  { group: "L", name: "L1", img: "./images/coll_l1.png", alg: "R' U' R U R' F' R U R' U' R' F R2", display: "12 j-perm" },
  { group: "L", name: "L2", img: "./images/coll_l2.png", alg: "R U R' U R U' R' U R U' R' U R U2 R'", display: "4515 4215 4215 4221" },
  { group: "L", name: "L3", img: "./images/coll_l3.png", alg: "R U2 R D R' U2 R D' R2", display: "4224 D 1554 D' 11" },
  { group: "L", name: "L4", img: "./images/coll_l4.png", alg: "R' U2 R' D' R U2 R' D R2", display: "1551 D' 4551 D 44" },
  { group: "L", name: "L5", img: "./images/coll_l5.png", alg: "x R' U R D' R' U' R D x'", display: "x 154D' 124D " },
  { group: "L", name: "L6", img: "./images/coll_l6.png", alg: "F R' F' r U R U' r'", display: "613(4) 542(1)" }
];

export const ollAlgorithms = [
  { group: "Awkward Shape", name: "29", img: "./images/oll_29.png", alg: "l D l' U l D' l2 U l U' l' U' l", display: "(7)D (8)5(7) D' (88)5(7) 2(8)2(7)" },
  { group: "Awkward Shape", name: "30", img: "./images/oll_30.png", alg: "r' D' r U' r' D r2 U' r' U r U r'", display: "(1)D' (4)2(1) D (44)2(1) 5(4)5(1) " },
  { group: "Awkward Shape", name: "41_1", img: "./images/oll_41_1.png", alg: "R U R' U R U2 R' F R U R' U' F'", display: "sune 6 4512 3" },
  { group: "Awkward Shape", name: "41_2", img: "./images/oll_41_2.png", alg: "L F' L' F L F' L' F L' U' L U L' U' L", display: "mirror: 1643 1643 4512 451" },
  { group: "Awkward Shape", name: "42_1", img: "./images/oll_42_1.png", alg: "R' U' R U' R' U2 R F R U R' U' F'", display: "backsune 6 4512 3" },
  { group: "Awkward Shape", name: "42_2", img: "./images/oll_42_2.png", alg: "R' F R F' R' F R F' R U R' U' R U R'", display: "1643 1643 4512 451" },
  { group: "Big Lightning Bolt", name: "39", img: "./images/oll_39.png", alg: "f' r U r' U' r' F r S", display: "(3) (4)5(1)2 (1)64S" }, 
  { group: "Big Lightning Bolt", name: "40", img: "./images/oll_40.png", alg: "R' F R U R' U' F' U R", display: "1645 12354" },
  { group: "C shape", name: "34", img: "./images/oll_34.png", alg: "f R f' U' r' U' R U M'", display: "(6)4(3)2 (1)245 M'" },
  { group: "C shape", name: "46", img: "./images/oll_46.png", alg: "R' U' R' F R F' U R", display: "1216 4354" },
  { group: "Corners_oriented", name: "28", img: "./images/oll_28.png", alg: "r U R' U' M U R U' R'", display: "(4)512 M 5421" },
  { group: "Corners_oriented", name: "57", img: "./images/oll_57.png", alg: "R U R' U' M' U R U' r'", display: "4512 M' 542(1)" },
  { group: "Cross", name: "21", img: "./images/oll_21.png", alg: "", display: "COLL" },
  { group: "Cross", name: "22", img: "./images/oll_22.png", alg: "", display: "COLL" },
  { group: "Cross", name: "23", img: "./images/oll_23.png", alg: "", display: "COLL" },
  { group: "Cross", name: "24", img: "./images/oll_24.png", alg: "", display: "COLL" },
  { group: "Cross", name: "25", img: "./images/oll_25.png", alg: "", display: "COLL" },
  { group: "Cross", name: "26", img: "./images/oll_26.png", alg: "", display: "COLL" },
  { group: "Cross", name: "27", img: "./images/oll_27.png", alg: "", display: "COLL" },
  { group: "Dot", name: "1", img: "./images/oll_1.png", alg: "R U2 R2 F R F' U2 R' F R F'", display: "4221 1643 22 1643" },
  { group: "Dot", name: "2", img: "./images/oll_2.png", alg: "f U R U' R' S' U R U' R' F'", display: "(6) 5421 S' 5421 3" },
  { group: "Dot", name: "3", img: "./images/oll_3.png", alg: "f U R U' R' S' R' F' R U R U' R'", display: "(6) 5421 S' 13 45421" },
  { group: "Dot", name: "4", img: "./images/oll_4.png", alg: "R' F R F' U' S R' U' R U R S'", display: "1643 2S 12454 S'" },
  { group: "Dot", name: "17", img: "./images/oll_17.png", alg: "F R' F' R U S' R U' R' S", display: "6134 5S' 421S" },
  { group: "Dot", name: "18", img: "./images/oll_18.png", alg: "F S' R U' R' S R U2 R' U' F' ", display: "6S' 421S 422123" },
  { group: "Dot", name: "19", img: "./images/oll_19.png", alg: "S' R U R' S U' R' F R F' ", display: "S' 451 S 2 1643" },
  { group: "Dot", name: "20", img: "./images/oll_20.png", alg: "S R' U' R U R U  R U' R' S'", display: "S 1245 45421 S'" },
  { group: "Fish shape", name: "9", img: "./images/oll_9.png", alg: "R U R' U' R' F R R U R' U' F'", display: "4512 164 4512 3" },
  { group: "Fish shape", name: "10", img: "./images/oll_10.png", alg: "R U R' U R' F R F' R U2 R'", display: "4515 1643 4221" },
  { group: "Fish shape", name: "35", img: "./images/oll_35.png", alg: "R U2 R' R' F R F' R U2 R'", display: "4221 1643 4221" },
  { group: "Fish shape", name: "37", img: "./images/oll_37.png", alg: "F R' F' R U R U' R'", display: "6134 5421" },
  { group: "I shape", name: "51_1", img: "./images/oll_51_1.png", alg: "F U R U' R' U R U' R' F'", display: "6 5421 5421 3" },
  { group: "I shape", name: "51_2", img: "./images/oll_51_2.png", alg: "R' U' R' F R F' R U' R' U2 R", display: "12 1643 421224" },
  { group: "I shape", name: "52", img: "./images/oll_52.png", alg: "R' F' U' F U' R U R' U R", display: "1326 245154" },
  { group: "I shape", name: "55_1", img: "./images/oll_55_1.png", alg: "R' F U R U' R2 F' R2 U R' U' R", display: "1654 211344 5124" },
  //{ group: "I shape", name: "55_2", img: "./images/oll_55_2.png", alg: "R U2 R2 U' R U' R' U2 F R F'", display: "422112 42122 643" },
  //{ group: "I shape", name: "55_3", img: "./images/oll_55_3.png", alg: "F U' R2 D R' U2 R D' R2 U F'", display: "6244 D 1224 D' 1153" },
  //{ group: "I shape", name: "55_4", img: "./images/oll_55_4.png", alg: "R' F R U R U' R2 F' R2 U' R' U R U R'", display: "1645 4211 34421 5451" },
  //{ group: "I shape", name: "56", img: "./images/oll_56.png", alg: "r U r' U R U' R' U R U' R' r U' r'", display: "(4)5(1)5 4215  421 (4)2(1)" },
  { group: "I shape", name: "56", img: "./images/oll_56.png", alg: "R' F' R U' L' U L U' L' U L R' F R", display: "1342 85728572 164" },
  { group: "Knight Move shape", name: "13", img: "./images/oll_13.png", alg: "F U R U' R' R' F' R U R U' R'", display: "6 5421 134 5421" },
  { group: "Knight Move shape", name: "14", img: "./images/oll_14.png", alg: "R' F R U R' F' R F U' F'", display: "1645 1346 23" },
  { group: "Knight Move shape", name: "16", img: "./images/oll_16.png", alg: "r' U' r R' U' R U r' U r", display: "(1)2(4) 1245 (1)5(4)" },
  { group: "Knight Move shape", name: "15", img: "./images/oll_15.png", alg: "r U r' R U R' U' r U' r'", display: "(4)5(1)  4512 (4)2(1)" },
  { group: "P shape", name: "31", img: "./images/oll_31.png", alg: "R' U' F U R U' R' F' R", display: "126 5421 34" },
  { group: "P shape", name: "32", img: "./images/oll_32.png", alg: "S R U R' U' R' F R f'", display: "S 4512 164(3)" },
  { group: "P shape", name: "43", img: "./images/oll_43.png", alg: "R' U' F' U F R", display: "123564" },
  { group: "P shape", name: "44", img: "./images/oll_44.png", alg: "f R U R' U' f'", display: "(6) 4512 (3)" },
  //{ group: "Small L shape", name: "47_1", img: "./images/oll_47_1.png", alg: "R' U' R' F R F' R' F R F' U R", display: "12 1643 1643 54 " },
  //{ group: "Small L shape", name: "47_2", img: "./images/oll_47_2.png", alg: "F U R U' R' F' R U R' U R U2 R'", display: "6 5421 3 sune" },
  { group: "Small L shape", name: "47", img: "./images/oll_47.png", alg: "F R' F' R U2 R U' R' U R U2 R'", display: "6134 55421 54221" },
  { group: "Small L shape", name: "48", img: "./images/oll_48.png", alg: "F R U R' U' R U R' U' F'", display: "6 4512 4512 3" },
  { group: "Small L shape", name: "49_1", img: "./images/oll_49_1.png", alg: "r U' r2 U r2 U r2 U' r", display: "(4)2(11)2(44)2(11)2(4)" },
  { group: "Small L shape", name: "49_2", img: "./images/oll_49_2.png", alg: "L' U2 L U L' U L F' L' U' L U F", display: "mirror: antisune 6 4512 3" },
  { group: "Small L shape", name: "50_1", img: "./images/oll_50_1.png", alg: "r' U r2 U' r2 U' r2 U r'", display: "(1)5(44)2(11)2(44)5(11)" },
  { group: "Small L shape", name: "50_2", img: "./images/oll_50_2.png", alg: "R U2 R' U' R U' R' F R U R' U' F'", display: "antisune 6 4512 3" },
  { group: "Small L shape", name: "53", img: "./images/oll_53.png", alg: "r' U' R U' R' U R U' R' U2 r", display: "(1)242 1542 122(4)" },
  { group: "Small L shape", name: "54", img: "./images/oll_54.png", alg: "r U R' U R U' R' U R U2 r'", display: "(4)515 4215 422(1)" },
  { group: "Small Lightning Bolt", name: "7", img: "./images/oll_7.png", alg: "r U R' U R U2 r'", display: "(4)515 422(1)" },
  { group: "Small Lightning Bolt", name: "8", img: "./images/oll_8.png", alg: "R U2 R' U2 R' F R F'", display: "422 122 1643" },
  { group: "Small Lightning Bolt", name: "11", img: "./images/oll_11.png", alg: "r U R' U R' F R F' R U2 r'", display: "(4)515 1643 422(1)" },
  { group: "Small Lightning Bolt", name: "12", img: "./images/oll_12.png", alg: "M' R' U' R U' R' U2 R U' M", display: "M' 124215542 M" },
  { group: "Square", name: "5", img: "./images/oll_5.png", alg: "r' U2 R U R' U r", display: "(1)224 515(4)" },
  { group: "Square", name: "6", img: "./images/oll_6.png", alg: "r U2 R' U' R U' r'", display: "(4)221 242(1)" },
  { group: "T shape", name: "33_1", img: "./images/oll_33_1.png", alg: "R U R' U' R' F R F'", display: "4512 1643" },
  { group: "T shape", name: "33_2", img: "./images/oll_33_2.png", alg: "F R U' R' U R U R' F'", display: "6 4215 4513" },
  { group: "T shape", name: "45", img: "./images/oll_45.png", alg: "F R U R' U' F'", display: "6 4512 3" },
  { group: "W shape", name: "36", img: "./images/oll_36.png", alg: "R' F' U' F2 U R U' R' F' R", display: "13266 5421 34" },
  { group: "W shape", name: "38", img: "./images/oll_38.png", alg: "R U R' U R U' R' U' R' F R F'", display: "4515 4212 1643" }
];

export const zbllAlgorithms = [
  { group: "T6", name: "ZBLLT61",img: "./images/zbll_t61.png", alg: "R' U' R U' R' U2 R U R' U2 R U R' U R",display: "backsune 5 antibacksune"},
  { group: "T6", name: "ZBLLT62",img: "./images/zbll_t62.png", alg: "R U R' U R U2 R' U' R U2 R' U' R U' R'",display: "sune 2 antisune"},
  { group: "T6", name: "ZBLLT64",img: "./images/zbll_t64.png", alg: "R U2 R' U' R U' R' U R U R' U R U2 R'",display: "antisune 5 sune"},
  { group: "T6", name: "ZBLLT66",img: "./images/zbll_t66.png", alg: "R' U2 R U R' U R U' R' U' R U' R' U2 R",display: "antibacksune 2 backsune"},
  { group: "T6", name: "ZBLLT69",img: "./images/zbll_t69.png", alg: "R U2 R' U' R U' R' R' U2 R U R' U R",display: "antisune antibacksune"},
  { group: "T6", name: "ZBLLT70",img: "./images/zbll_t70.png", alg: "R' U2 R U R' U R R U2 R' U' R U' R'",display: "antibacksune antisune"},
  { group: "T6", name: "ZBLLT72",img: "./images/zbll_t72.png", alg: "R U R' U R U2 R' U2 R' U' R U' R' U2 R",display: "sune 22 backsune"},

  { group: "U6", name: "ZBLLU61",img: "./images/zbll_u61.png", alg: "R U R' U R U2 R' U R U2 R' U' R U' R'",display: "sune 5 antisune" },
  { group: "U6", name: "ZBLLU62",img: "./images/zbll_u62.png", alg: "R' U' R U' R' U2 R U' R' U2 R U R' U R",display: "backsune 2 antibacksune" },
  { group: "U6", name: "ZBLLU63",img: "./images/zbll_u63.png", alg: "R U2 R' U' R U' R' U' R U R' U R U2 R'",display: "antisune 2 sune" },
  { group: "U6", name: "ZBLLU65",img: "./images/zbll_u65.png", alg: "R' U2 R U R' U R U R' U' R U' R' U2 R",display: "antibacksune 5 backsune" },
  { group: "U6", name: "ZBLLU69",img: "./images/zbll_u69.png", alg: "R' U' R U' R' U2 R R U R' U R U2 R'",display: "backsune sune" },
  { group: "U6", name: "ZBLLU70",img: "./images/zbll_u70.png", alg: "R U R' U R U2 R' R' U' R U' R' U2 R",display: "sune backsune" },
  { group: "U6", name: "ZBLLU72",img: "./images/zbll_u72.png", alg: "R U2 R' U' R U' R' U2 R' U2 R U R' U R",display: "antisune 22 antibacksune" },
  
  { group: "L6", name: "ZBLLL71",img: "./images/zbll_l71.png", alg: "R U R' U R U2 R' R U R' U R U2 R' R U R' U R U2 R'",display: "4515 4215 4215 4221" },
  { group: "L6", name: "ZBLLL63",img: "./images/zbll_l63.png", alg: "R U R' U R U2 R' U R' U' R U' R' U2 R",display: "sune 5 backsune" },
  { group: "L6", name: "ZBLLL67",img: "./images/zbll_l67.png", alg: "R' U' R U' R' U2 R U' R U R' U R U2 R'", display: "backsune 2 sune" },
  { group: "L6", name: "ZBLLL69",img: "./images/zbll_l69.png", alg: "R' U2 R U R' U R U2 R' U' R U' R' U2 R", display: "antibacksune 22 backsune" },
  { group: "L6", name: "ZBLLL70",img: "./images/zbll_l70.png", alg: "R' U' R U' R' U2 R U2 R' U2 R U R' U R", display: "backsune 22 antibacksune" },
  { group: "L6", name: "ZBLLL62",img: "./images/zbll_l62.png", alg: "R U2 R' U' R U' R' U R' U2 R U R' U R",display: "antisune 5 antibacksune" },
  { group: "L6", name: "ZBLLL65",img: "./images/zbll_l65.png", alg: "R' U2 R U R' U R U' R U2 R' U' R U' R'", display: "antibacksune 2 antisune" },

]
  /**sune R U R' U R U2 R'
 * anti-sune R U2 R' U' R U' R'
 * back-sune R' U' R U' R' U2 R
 * anti-back-sune R' U2 R U R' U R
 * **/
export const wvAlgorithms = [
  {group: "3 corners", name:"oriented", img: "./images/wv_oriented.png", alg: "L' U2 R U R' U2 L", display: "855 451 557"},
  {group: "2 corners", name:"rectangle1", img: "./images/wv_rectangle1.png", alg: "U' R' F R U R U' R' F'", display: "2 1645 4213"},
  {group: "2 corners", name:"rectangle2", img: "./images/wv_rectangle2.png", alg: "R U' R'", display: "421"},
  {group: "2 corners", name:"snake1", img: "./images/wv_snake1.png", alg: "R U' R' U R' U' R U' R' U2 R", display: "4215 backsune"},
  {group: "2 corners", name:"snake2", img: "./images/wv_snake2.png", alg: "R2 D R' U' R D' R2", display: "44D 124D' 11"},
  {group: "2 corners", name:"tank1", img: "./images/wv_tank1.png", alg: "R U R' U' R U' R'", display: "4512 421"},
  {group: "2 corners", name:"tank2", img: "./images/wv_tank2.png", alg: "U' R U' R' U2 R U' R' U2 R U R'", display: "2 42155 42155 451"},
  {group: "1 corner", name:"adjacent1", img: "./images/wv_adjacent1.png", alg: "U' R' F2 R2 U' R' U' R U R' F2", display: "2 166442 1245166"},
  {group: "1 corner", name:"adjacent2", img: "./images/wv_adjacent2.png", alg: "U' R' F' R U2 R U2 R' F", display: "2134 554221 6"},
  {group: "1 corner", name:"adjacent3", img: "./images/wv_adjacent3.png", alg: "U R U2 R'", display: "54221"},
  {group: "1 corner", name:"adjacent4", img: "./images/wv_adjacent4.png", alg: "U R U' R' U' R' F R U R U' R' F'", display: "5421 2164 5421 3"},
  {group: "1 corner", name:"bowtie1", img: "./images/wv_bowtie1.png", alg: "U' L' U R U' R' L", display: "28542 17"},
  {group: "1 corner", name:"bowtie2", img: "./images/wv_bowtie2.png", alg: "U R2 D R' U2 R D' R2", display: "544D 1224D' 11"},
  {group: "1 corner", name:"bowtie3", img: "./images/wv_bowtie3.png", alg: "U R U2 R2 U' R U' R' U2 R", display: "54221 backsune"},
  {group: "1 corner", name:"bowtie4", img: "./images/wv_bowtie4.png", alg: "U' R' F2 R F2 U L' U L", display: "2 (8)55 (7)33 5857"},
  {group: "1 corner", name:"gun1", img: "./images/wv_gun1.png", alg: "R U R2 U' R2 U' R2 U2 R", display: "45112 44211224"},
  {group: "1 corner", name:"gun2", img: "./images/wv_gun2.png", alg: "U R' U' R2 U' R2 U2 R", display: "51244 211224"},
  {group: "1 corner", name:"gun3", img: "./images/wv_gun3.png", alg: "U R U' R' U R U2 R'", display: "5421 54221"},
  {group: "1 corner", name:"gun4", img: "./images/wv_gun4.png", alg: "R U' R' U R U2 R2 U' R2 U' R2 U2 R", display: "4215 std_pi"},
  {group: "0 corner", name:"h1", img: "./images/wv_h1.png", alg: "U R2 U R' U R' U' R U R U2 R2", display: "5 44515 1245 42211"},
  {group: "0 corner", name:"h2", img: "./images/wv_h2.png", alg: "U R U' R' U R U' R' U R U2 R'", display: "5421 5421 54221"},
  {group: "0 corner", name:"pi1", img: "./images/wv_pi1.png", alg: "R2 D R' U R D' R' U2 R'", display: "44D 124 D' 1551"},
  {group: "0 corner", name:"pi2", img: "./images/wv_pi2.png", alg: "R U' R2 U2 R U R' U R", display: "421122 45154"},
  {group: "0 corner", name:"pi3", img: "./images/wv_pi3.png", alg: "U R U2 R2 U2 R U R' U R", display: "54221 antibacksune"},
  {group: "0 corner", name:"pi4", img: "./images/wv_pi4.png", alg: "R U' R2 U' R U' R' U2 R", display: "42112 421224"},
  {group: "0 corner", name:"sune1", img: "./images/wv_sune1.png", alg: "R U R' U' R U R' U' R U' R'", display: "4512 4512 421"},
  {group: "0 corner", name:"sune2", img: "./images/wv_sune2.png", alg: "R U' R' U' R U R' U R U2 R'", display: "4212 sune"}
]

// speffz.js
export const BLIND_ORDER = {
  edges:   ["UF","UR","UB","UL","DF","DR","DB","DL","FR","FL","BR","BL"],
  corners: ["UFR","URB","UBL","ULF","DFR","DLF","DBL","DRB"],
};

export const BLIND_SCHEME = {
  edges: {
    UF: { stickers: { U: { letter: "C", setup: "" },   F: { letter: "I", setup: "U2 r'" } } },
    UR: { stickers: { U: { letter: "B", setup: "U" },  R: { letter: "M", setup: "R' F'" } } },
    UB: { stickers: { U: { letter: "A", setup: "U2" }, B: { letter: "Q", setup: "r'" } } },
    UL: { stickers: { U: { letter: "D", setup: "U'" }, L: { letter: "E", setup: "L F" } } },
    DF: { stickers: { D: { letter: "U", setup: "F2" }, F: { letter: "K", setup: "r" } } },
    DR: { stickers: { D: { letter: "V", setup: "D' F2" }, R: { letter: "O", setup: "D' r" } } },
    DB: { stickers: { D: { letter: "W", setup: "M2" }, B: { letter: "S", setup: "M U2" } } },
    DL: { stickers: { D: { letter: "X", setup: "D F2" }, L: { letter: "G", setup: "D r" } } },
    FR: { stickers: { F: { letter: "J", setup: "R U" }, R: { letter: "P", setup: "F'" } } },
    BR: { stickers: { B: { letter: "T", setup: "R' U" }, R: { letter: "N", setup: "R2 F'" } } },
    BL: { stickers: { B: { letter: "R", setup: "L U'" }, L: { letter: "H", setup: "L2 F" } } },
    FL: { stickers: { F: { letter: "L", setup: "L' U'" }, L: { letter: "F", setup: "F" } } },
  },
  corners: {
    UFR: { stickers: { U: { letter: "C", setup: "" },   F: { letter: "J", setup: "R U" },   R: { letter: "M", setup: "F' U'" } } },
    URB: { stickers: { U: { letter: "B", setup: "U" },  R: { letter: "N", setup: "R2 F'" }, B: { letter: "Q", setup: "R'" } } },
    UBL: { stickers: { U: { letter: "A", setup: "U2" }, B: { letter: "R", setup: "L U'" },  L: { letter: "E", setup: "L F" } } },
    ULF: { stickers: { U: { letter: "D", setup: "U'" }, L: { letter: "F", setup: "F" },     F: { letter: "I", setup: "F2 R" } } },
    DFR: { stickers: { D: { letter: "V", setup: "F2 U'" }, F: { letter: "K", setup: "R" },  R: { letter: "P", setup: "F'" } } },
    DRB: { stickers: { D: { letter: "W", setup: "R2" },   R: { letter: "O", setup: "R F'" }, B:{ letter: "T", setup: "R' U" } } },
    DBL: { stickers: { D: { letter: "X", setup: "D' R2" }, B: { letter: "S", setup: "D2 R" }, L:{ letter: "H", setup: "D2 F'" } } },
    DLF: { stickers: { D: { letter: "U", setup: "F2" },    L: { letter: "G", setup: "F U'" }, F:{ letter: "L", setup: "F' R" } } },
  }
};
